version: '2' # version  docker compose
services:

  # Php container
  php:
    build: ./docker/php #  path  Dockerfile container
    working_dir: /var/www/laravel # directory
    volumes:
    - ./:/var/www/laravel

  # Web Server nginx container
  nginx:
    build: ./docker/nginx
    working_dir: /var/www/laravel # directory for work
    volumes_from:
    - php #  volume for php container
    ports:
    - 8000:80 # port {host}:{container}

  # mysql container
  database:
    image: mysql:5.7
    volumes:
    - ./mysql/data:/var/lib/mysql #  volume database
    environment:
    #  config mysql envionment for more information https://hub.docker.com/_/mysql/
    - MYSQL_DATABASE=laravel #  database container
    - MYSQL_USER=user # username  database
    - MYSQL_PASSWORD=password # password database
    - MYSQL_ROOT_PASSWORD=root # password  root database
    ports:
    - "3306:3306" # port  {host}:{container}

  composer: #  container for install package laravel
    build: ./docker/php # dockerfile  container php
    working_dir: /var/www/laravel
    volumes_from:
    - php
    command: "composer install" #  install package dependencies


  # Php myadmin (optional) explore database
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
    - 8890:80
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=database
    restart: always
    depends_on:
    - database
